# Generated by Django 3.2.25 on 2025-05-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=30)),
                ('publicado_em', models.DateField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
                ('genero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.genero')),
            ],
        ),
    ]
