# Generated by Django 3.2.25 on 2025-05-15 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('livro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.CheckConstraint(check=models.Q(('data_devolucao__gte', django.db.models.expressions.F('data_emprestimo'))), name='devolucao_nao_menor_emprestimo'),
        ),
    ]
